var newObject = [
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '011 - Cash Grains',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '011',
        'siccodetext-3digit-industry': 'Cash Grains',
        'noofcompanies-3digit-industry': '1220',
        'empsize-3digit-industry': undefined,
        'siccode-4digit': '0111',
        'siccodetext-4digit-industry': 'Wheat',
        'noofcompanies-4digit-industry': '268',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '011 - Cash Grains',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '011',
        'siccodetext-3digit-industry': 'Cash Grains',
        'noofcompanies-3digit-industry': '1220',
        'empsize-3digit-industry': undefined,
        'siccode-4digit': '0112',
        'siccodetext-4digit-industry': 'Rice',
        'noofcompanies-4digit-industry': '22',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 013 - Field Crops, except Cash Grains',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '013',
        'siccodetext-3digit-industry': ' Field Crops, except Cash Grains',
        'noofcompanies-3digit-industry': '2295',
        'empsize-3digit-industry': undefined,
        'siccode-4digit': '0131',
        'siccodetext-4digit-industry': 'Cotton',
        'noofcompanies-4digit-industry': '49',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 013 - Field Crops, except Cash Grains',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '013',
        'siccodetext-3digit-industry': ' Field Crops, except Cash Grains',
        'noofcompanies-3digit-industry': '2295',
        'empsize-3digit-industry': undefined,
        'siccode-4digit': '0132',
        'siccodetext-4digit-industry': 'Tobacco',
        'noofcompanies-4digit-industry': '23',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '017 - Fruits and Tree Nuts',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '017',
        'siccodetext-3digit-industry': 'Fruits and Tree Nuts',
        'noofcompanies-3digit-industry': '2881',
        'empsize-3digit-industry': '3969',
        'siccode-4digit': '0174',
        'siccodetext-4digit-industry': 'Citrus Fruits',
        'noofcompanies-4digit-industry': '83',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '017 - Fruits and Tree Nuts',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '017',
        'siccodetext-3digit-industry': 'Fruits and Tree Nuts',
        'noofcompanies-3digit-industry': '2881',
        'empsize-3digit-industry': '3969',
        'siccode-4digit': '0175',
        'siccodetext-4digit-industry': 'Deciduous Tree Fruits',
        'noofcompanies-4digit-industry': '1290',
        'empsize-4digit-industry': '3016',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '017 - Fruits and Tree Nuts',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '017',
        'siccodetext-3digit-industry': 'Fruits and Tree Nuts',
        'noofcompanies-3digit-industry': '2881',
        'empsize-3digit-industry': '3969',
        'siccode-4digit': '0179',
        'siccodetext-4digit-industry':
            ' Fruits and Tree Nuts, Not Elsewhere Classified',
        'noofcompanies-4digit-industry': '43',
        'empsize-4digit-industry': '774',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '018 - Horticultural Specialties',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '018',
        'siccodetext-3digit-industry': 'Horticultural Specialties',
        'noofcompanies-3digit-industry': '3330',
        'empsize-3digit-industry': '40861',
        'siccode-4digit': '0181',
        'siccodetext-4digit-industry':
            'Ornamental Floriculture and Nursery Products',
        'noofcompanies-4digit-industry': '3006',
        'empsize-4digit-industry': '40861',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '018 - Horticultural Specialties',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '018',
        'siccodetext-3digit-industry': 'Horticultural Specialties',
        'noofcompanies-3digit-industry': '3330',
        'empsize-3digit-industry': '40861',
        'siccode-4digit': '0182',
        'siccodetext-4digit-industry': 'Food Crops Grown Under Cover',
        'noofcompanies-4digit-industry': '324',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 019 - General Farms, Primarily Crop',
        'siccode-2digit': '01',
        'siccodetext-2digit-industry': 'Agricultural Production - Crops',
        'siccode-3digit': '019',
        'siccodetext-3digit-industry': ' General Farms, Primarily Crop',
        'noofcompanies-3digit-industry': '23711',
        'empsize-3digit-industry': '237167',
        'siccode-4digit': '0191',
        'siccodetext-4digit-industry': ' General Farms, Primarily Crop',
        'noofcompanies-4digit-industry': '23711',
        'empsize-4digit-industry': '237167',
    },
    {
        Industry: '',
        '3 Digit SIC Code': '',
        'siccode-2digit': '',
        'siccodetext-2digit-industry': '',
        'siccode-3digit': '',
        'siccodetext-3digit-industry': '',
        'noofcompanies-3digit-industry': '',
        'empsize-3digit-industry': '',
        'siccode-4digit': '',
        'siccodetext-4digit-industry': '',
        'noofcompanies-4digit-industry': '',
        'empsize-4digit-industry': '',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 021 - Livestock, except Dairy, Poultry, etc.',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '021',
        'siccodetext-3digit-industry':
            ' Livestock, except Dairy, Poultry, etc.',
        'noofcompanies-3digit-industry': '1593',
        'empsize-3digit-industry': '6',
        'siccode-4digit': '0211',
        'siccodetext-4digit-industry': 'Beef Cattle Feedlots',
        'noofcompanies-4digit-industry': '711',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 021 - Livestock, except Dairy, Poultry, etc.',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '021',
        'siccodetext-3digit-industry':
            ' Livestock, except Dairy, Poultry, etc.',
        'noofcompanies-3digit-industry': '1593',
        'empsize-3digit-industry': '6',
        'siccode-4digit': '0212',
        'siccodetext-4digit-industry': ' Beef Cattle, except Feedlots',
        'noofcompanies-4digit-industry': '603',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 021 - Livestock, except Dairy, Poultry, etc.',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '021',
        'siccodetext-3digit-industry':
            ' Livestock, except Dairy, Poultry, etc.',
        'noofcompanies-3digit-industry': '1593',
        'empsize-3digit-industry': '6',
        'siccode-4digit': '0213',
        'siccodetext-4digit-industry': 'Hogs',
        'noofcompanies-4digit-industry': '195',
        'empsize-4digit-industry': '6',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '027 - Animal Specialties',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '027',
        'siccodetext-3digit-industry': 'Animal Specialties',
        'noofcompanies-3digit-industry': '1487',
        'empsize-3digit-industry': '248',
        'siccode-4digit': '0272',
        'siccodetext-4digit-industry': 'Horses and Other Equines',
        'noofcompanies-4digit-industry': '357',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '027 - Animal Specialties',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '027',
        'siccodetext-3digit-industry': 'Animal Specialties',
        'noofcompanies-3digit-industry': '1487',
        'empsize-3digit-industry': '248',
        'siccode-4digit': '0273',
        'siccodetext-4digit-industry': 'Animal Aquaculture',
        'noofcompanies-4digit-industry': '482',
        'empsize-4digit-industry': '248',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '027 - Animal Specialties',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '027',
        'siccodetext-3digit-industry': 'Animal Specialties',
        'noofcompanies-3digit-industry': '1487',
        'empsize-3digit-industry': '248',
        'siccode-4digit': '0279',
        'siccodetext-4digit-industry':
            ' Animal Specialties, Not Elsewhere Classified',
        'noofcompanies-4digit-industry': '566',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 029 - General Farms, Primarily Livestock',
        'siccode-2digit': '02',
        'siccodetext-2digit-industry': 'Agricultural Production - Livestock',
        'siccode-3digit': '029',
        'siccodetext-3digit-industry': ' General Farms, Primarily Livestock',
        'noofcompanies-3digit-industry': '6645',
        'empsize-3digit-industry': '139916',
        'siccode-4digit': '0291',
        'siccodetext-4digit-industry': ' General Farms, Primarily Livestock',
        'noofcompanies-4digit-industry': '6645',
        'empsize-4digit-industry': '139916',
    },
    {
        Industry: '',
        '3 Digit SIC Code': '',
        'siccode-2digit': '',
        'siccodetext-2digit-industry': '',
        'siccode-3digit': '',
        'siccodetext-3digit-industry': '',
        'noofcompanies-3digit-industry': '',
        'empsize-3digit-industry': '',
        'siccode-4digit': '',
        'siccodetext-4digit-industry': '',
        'noofcompanies-4digit-industry': '',
        'empsize-4digit-industry': '',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '071 - Soil Preparation Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '071',
        'siccodetext-3digit-industry': 'Soil Preparation Services',
        'noofcompanies-3digit-industry': '171',
        'empsize-3digit-industry': undefined,
        'siccode-4digit': '0711',
        'siccodetext-4digit-industry': 'Soil Preparation Services',
        'noofcompanies-4digit-industry': '171',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '072 - Crop Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '072',
        'siccodetext-3digit-industry': 'Crop Services',
        'noofcompanies-3digit-industry': '2402',
        'empsize-3digit-industry': '4542',
        'siccode-4digit': '0721',
        'siccodetext-4digit-industry': 'Crop Planting and Protection',
        'noofcompanies-4digit-industry': '1410',
        'empsize-4digit-industry': '4542',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '072 - Crop Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '072',
        'siccodetext-3digit-industry': 'Crop Services',
        'noofcompanies-3digit-industry': '2402',
        'empsize-3digit-industry': '4542',
        'siccode-4digit': '0722',
        'siccodetext-4digit-industry': ' Crop Harvesting, Primarily by Machine',
        'noofcompanies-4digit-industry': '132',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '072 - Crop Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '072',
        'siccodetext-3digit-industry': 'Crop Services',
        'noofcompanies-3digit-industry': '2402',
        'empsize-3digit-industry': '4542',
        'siccode-4digit': '0723',
        'siccodetext-4digit-industry':
            ' Crop Preparation Services for Market, except Cotton Ginning',
        'noofcompanies-4digit-industry': '528',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '072 - Crop Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '072',
        'siccodetext-3digit-industry': 'Crop Services',
        'noofcompanies-3digit-industry': '2402',
        'empsize-3digit-industry': '4542',
        'siccode-4digit': '0724',
        'siccodetext-4digit-industry': 'Cotton Ginning',
        'noofcompanies-4digit-industry': '332',
        'empsize-4digit-industry': undefined,
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '074 - Veterinary Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '074',
        'siccodetext-3digit-industry': 'Veterinary Services',
        'noofcompanies-3digit-industry': '28859',
        'empsize-3digit-industry': '528510',
        'siccode-4digit': '0741',
        'siccodetext-4digit-industry': 'Veterinary Services for Livestock',
        'noofcompanies-4digit-industry': 'NA',
        'empsize-4digit-industry': 'NA',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '074 - Veterinary Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '074',
        'siccodetext-3digit-industry': 'Veterinary Services',
        'noofcompanies-3digit-industry': '28859',
        'empsize-3digit-industry': '528510',
        'siccode-4digit': '0742',
        'siccodetext-4digit-industry':
            'Veterinary Services for Animal Specialties',
        'noofcompanies-4digit-industry': '28859',
        'empsize-4digit-industry': '528459',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 075 - Animal Services, except Veterinary',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '075',
        'siccodetext-3digit-industry': ' Animal Services, except Veterinary',
        'noofcompanies-3digit-industry': '40600',
        'empsize-3digit-industry': '77488',
        'siccode-4digit': '0751',
        'siccodetext-4digit-industry': ' Livestock Services, except Veterinary',
        'noofcompanies-4digit-industry': '1616',
        'empsize-4digit-industry': '8370',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': ' 075 - Animal Services, except Veterinary',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '075',
        'siccodetext-3digit-industry': ' Animal Services, except Veterinary',
        'noofcompanies-3digit-industry': '40600',
        'empsize-3digit-industry': '77488',
        'siccode-4digit': '0752',
        'siccodetext-4digit-industry':
            ' Animal Specialty Services, except Veterinary',
        'noofcompanies-4digit-industry': '38984',
        'empsize-4digit-industry': '69118',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '076 - Farm Labor and Management Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '076',
        'siccodetext-3digit-industry': 'Farm Labor and Management Services',
        'noofcompanies-3digit-industry': '1646',
        'empsize-3digit-industry': '129109',
        'siccode-4digit': '0761',
        'siccodetext-4digit-industry':
            'Farm Labor Contractors and Crew Leaders',
        'noofcompanies-4digit-industry': '191',
        'empsize-4digit-industry': '58',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '076 - Farm Labor and Management Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '076',
        'siccodetext-3digit-industry': 'Farm Labor and Management Services',
        'noofcompanies-3digit-industry': '1646',
        'empsize-3digit-industry': '129109',
        'siccode-4digit': '0762',
        'siccodetext-4digit-industry': 'Farm Management Services',
        'noofcompanies-4digit-industry': '1455',
        'empsize-4digit-industry': '129051',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '078 - Landscape and Horticultural Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '078',
        'siccodetext-3digit-industry': 'Landscape and Horticultural Services',
        'noofcompanies-3digit-industry': '86281',
        'empsize-3digit-industry': '846670',
        'siccode-4digit': '0781',
        'siccodetext-4digit-industry': 'Landscape Counseling and Planning',
        'noofcompanies-4digit-industry': '6303',
        'empsize-4digit-industry': '185904',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '078 - Landscape and Horticultural Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '078',
        'siccodetext-3digit-industry': 'Landscape and Horticultural Services',
        'noofcompanies-3digit-industry': '86281',
        'empsize-3digit-industry': '846670',
        'siccode-4digit': '0782',
        'siccodetext-4digit-industry': 'Lawn and Garden Services',
        'noofcompanies-4digit-industry': '61043',
        'empsize-4digit-industry': '637206',
    },
    {
        Industry: ' Agriculture, Forestry, Fishing',
        '3 Digit SIC Code': '078 - Landscape and Horticultural Services',
        'siccode-2digit': '07',
        'siccodetext-2digit-industry': 'Agricultural services',
        'siccode-3digit': '078',
        'siccodetext-3digit-industry': 'Landscape and Horticultural Services',
        'noofcompanies-3digit-industry': '86281',
        'empsize-3digit-industry': '846670',
        'siccode-4digit': '0783',
        'siccodetext-4digit-industry': 'Ornamental Shrub and Tree Services',
        'noofcompanies-4digit-industry': '18935',
        'empsize-4digit-industry': '23560',
    },
]

module.exports = newObject
